services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/
    working_dir: /var/www/
    depends_on:
      - db
    networks:
      - app-network
    container_name: app

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: iliad_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app-network

  meilisearch:
    image: getmeili/meilisearch:v0.28
    container_name: meilisearch
    environment:
        - MEILI_ENV=development
    ports:
      - "7700:7700" 
    volumes:
      - ./meili_data:/meili_data 
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  meilisearch-data:

